export const MOVEMENTS_DB = [
  // ─── HALTEROFILIA ───────────────────────────────────────────
  { id: 'cj',     name: 'Clean & Jerk',         category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'cl',     name: 'Clean',                 category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'pc',     name: 'Power Clean',           category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'hpc',    name: 'Hang Power Clean',      category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'hc',     name: 'Hang Clean',            category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'lhpc',   name: 'Low Hang Power Clean',  category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'blkcl',  name: 'Block Clean',           category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'mscl',   name: 'Muscle Clean',          category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'clpull', name: 'Clean Pull',            category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'sn',     name: 'Snatch',                category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'psn',    name: 'Power Snatch',          category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'hpsn',   name: 'Hang Power Snatch',     category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'hsn',    name: 'Hang Snatch',           category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'blksn',  name: 'Block Snatch',          category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'mssn',   name: 'Muscle Snatch',         category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'snpull', name: 'Snatch Pull',           category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'snbal',  name: 'Snatch Balance',        category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'tallsn', name: 'Tall Snatch',           category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'tallcl', name: 'Tall Clean',            category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'ohs',    name: 'Overhead Squat',        category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'sj',     name: 'Split Jerk',            category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'pj',     name: 'Push Jerk',             category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'pjerk',  name: 'Power Jerk',            category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'sqjerk', name: 'Squat Jerk',            category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },
  { id: 'bnkjrk', name: 'Behind Neck Jerk',      category: 'Halterofilia', equipment: 'Barbell', unit: 'reps' },

  // ─── POWERLIFTING ────────────────────────────────────────────
  { id: 'bs',      name: 'Back Squat',           category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'fs',      name: 'Front Squat',          category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'pausesq', name: 'Pause Squat',          category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'boxsq',   name: 'Box Squat',            category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'dl',      name: 'Deadlift',             category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'rdl',     name: 'Romanian Deadlift',    category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'cgdl',    name: 'Sumo Deadlift',        category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'bp',      name: 'Bench Press',          category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'incbp',   name: 'Incline Bench Press',  category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'cgbp',    name: 'Close Grip Bench',     category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'sp',      name: 'Strict Press',         category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'pp',      name: 'Push Press',           category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'thruster',name: 'Thruster',             category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'pc_str',  name: 'Pendlay Row',          category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'gm',      name: 'Good Morning',         category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },
  { id: 'hipth',   name: 'Hip Thrust',           category: 'Powerlifting', equipment: 'Barbell', unit: 'reps' },

  // ─── FUERZA ─────────────────────────────────────────────────
  { id: 'dbthruster', name: 'DB Thruster',       category: 'Fuerza', equipment: 'Dumbbell',   unit: 'reps' },
  { id: 'dbsn',       name: 'DB Snatch',         category: 'Fuerza', equipment: 'Dumbbell',   unit: 'reps' },
  { id: 'dbcl',       name: 'DB Clean',          category: 'Fuerza', equipment: 'Dumbbell',   unit: 'reps' },
  { id: 'dblunge',    name: 'DB Lunge',          category: 'Fuerza', equipment: 'Dumbbell',   unit: 'reps' },
  { id: 'dbrow',      name: 'DB Row',            category: 'Fuerza', equipment: 'Dumbbell',   unit: 'reps' },
  { id: 'kbsw',       name: 'KB Swing',          category: 'Fuerza', equipment: 'Kettlebell', unit: 'reps' },
  { id: 'kbswam',     name: 'KB Swing Americano',category: 'Fuerza', equipment: 'Kettlebell', unit: 'reps' },
  { id: 'kbcl',       name: 'KB Clean',          category: 'Fuerza', equipment: 'Kettlebell', unit: 'reps' },
  { id: 'kbpp',       name: 'KB Push Press',     category: 'Fuerza', equipment: 'Kettlebell', unit: 'reps' },
  { id: 'kbsn',       name: 'KB Snatch',         category: 'Fuerza', equipment: 'Kettlebell', unit: 'reps' },
  { id: 'gob',        name: 'Goblet Squat',      category: 'Fuerza', equipment: 'Kettlebell', unit: 'reps' },
  { id: 'fmcarry',    name: 'Farmers Carry',     category: 'Fuerza', equipment: 'Kettlebell', unit: 'metros' },
  { id: 'stcarry',    name: 'Suitcase Carry',    category: 'Fuerza', equipment: 'Kettlebell', unit: 'metros' },
  { id: 'ohcarry',    name: 'Overhead Carry',    category: 'Fuerza', equipment: 'Kettlebell', unit: 'metros' },
  { id: 'wbs',        name: 'Wall Ball',         category: 'Fuerza', equipment: 'Wall Ball',  unit: 'reps' },
  { id: 'boxjump',    name: 'Box Jump',          category: 'Fuerza', equipment: 'Box',        unit: 'reps' },
  { id: 'boxjumpov',  name: 'Box Jump Over',     category: 'Fuerza', equipment: 'Box',        unit: 'reps' },
  { id: 'stepup',     name: 'Step Up',           category: 'Fuerza', equipment: 'Box',        unit: 'reps' },
  { id: 'lunge',      name: 'Lunge',             category: 'Fuerza', equipment: 'BW',         unit: 'reps' },
  { id: 'pistol',     name: 'Pistol Squat',      category: 'Fuerza', equipment: 'BW',         unit: 'reps' },
  { id: 'sbcl',       name: 'Sandbag Clean',     category: 'Fuerza', equipment: 'Sandbag',    unit: 'reps' },
  { id: 'sbcarry',    name: 'Sandbag Carry',     category: 'Fuerza', equipment: 'Sandbag',    unit: 'metros' },
  { id: 'bearcrawl',  name: 'Bear Crawl',        category: 'Fuerza', equipment: 'BW',         unit: 'metros' },

  // ─── GIMNÁSTICOS ────────────────────────────────────────────
  { id: 'pu',      name: 'Pull-up',              category: 'Gimnásticos', equipment: 'Barra',   unit: 'reps' },
  { id: 'pu_strict',name: 'Strict Pull-up',      category: 'Gimnásticos', equipment: 'Barra',   unit: 'reps' },
  { id: 'kpu',     name: 'Kipping Pull-up',      category: 'Gimnásticos', equipment: 'Barra',   unit: 'reps' },
  { id: 'jpu',     name: 'Jumping Pull-up',      category: 'Gimnásticos', equipment: 'Barra',   unit: 'reps' },
  { id: 'c2b',     name: 'C2B Pull-up',          category: 'Gimnásticos', equipment: 'Barra',   unit: 'reps' },
  { id: 'bmu',     name: 'Bar Muscle-Up',        category: 'Gimnásticos', equipment: 'Barra',   unit: 'reps' },
  { id: 'rmu',     name: 'Ring Muscle-Up',       category: 'Gimnásticos', equipment: 'Anillas', unit: 'reps' },
  { id: 'ttb',     name: 'Toes to Bar',          category: 'Gimnásticos', equipment: 'Barra',   unit: 'reps' },
  { id: 'k2e',     name: 'Knees to Elbow',       category: 'Gimnásticos', equipment: 'Barra',   unit: 'reps' },
  { id: 'scap',    name: 'Scap Pull-up',         category: 'Gimnásticos', equipment: 'Barra',   unit: 'reps' },
  { id: 'ringrow', name: 'Ring Row',             category: 'Gimnásticos', equipment: 'Anillas', unit: 'reps' },
  { id: 'dip',     name: 'Ring Dip',             category: 'Gimnásticos', equipment: 'Anillas', unit: 'reps' },
  { id: 'sdip',    name: 'Strict Ring Dip',      category: 'Gimnásticos', equipment: 'Anillas', unit: 'reps' },
  { id: 'bardip',  name: 'Bar Dip',              category: 'Gimnásticos', equipment: 'Barra',   unit: 'reps' },
  { id: 'hspu',    name: 'HSPU Kipping',         category: 'Gimnásticos', equipment: 'Pared',   unit: 'reps' },
  { id: 'shspu',   name: 'HSPU Estricto',        category: 'Gimnásticos', equipment: 'Pared',   unit: 'reps' },
  { id: 'hsw',     name: 'Handstand Walk',       category: 'Gimnásticos', equipment: 'BW',      unit: 'metros' },
  { id: 'hsh',     name: 'Handstand Hold',       category: 'Gimnásticos', equipment: 'BW',      unit: 'seg' },
  { id: 'ww',      name: 'Wall Walk',            category: 'Gimnásticos', equipment: 'Pared',   unit: 'reps' },
  { id: 'rc',      name: 'Rope Climb',           category: 'Gimnásticos', equipment: 'Cuerda',  unit: 'reps' },
  { id: 'lrc',     name: 'Legless Rope Climb',   category: 'Gimnásticos', equipment: 'Cuerda',  unit: 'reps' },
  { id: 'pushup',  name: 'Push-up',              category: 'Gimnásticos', equipment: 'BW',      unit: 'reps' },
  { id: 'hrpu',    name: 'Hand Release Push-up', category: 'Gimnásticos', equipment: 'BW',      unit: 'reps' },
  { id: 'ringpu',  name: 'Push-up en Anillas',   category: 'Gimnásticos', equipment: 'Anillas', unit: 'reps' },
  { id: 'burpee',  name: 'Burpee',               category: 'Gimnásticos', equipment: 'BW',      unit: 'reps' },
  { id: 'burpeebox',name: 'Burpee Box Jump Over',category: 'Gimnásticos', equipment: 'Box',     unit: 'reps' },
  { id: 'barbur',  name: 'Bar Burpee',           category: 'Gimnásticos', equipment: 'Barbell', unit: 'reps' },
  { id: 'airsq',   name: 'Air Squat',            category: 'Gimnásticos', equipment: 'BW',      unit: 'reps' },
  { id: 'jumpsq',  name: 'Jump Squat',           category: 'Gimnásticos', equipment: 'BW',      unit: 'reps' },
  { id: 'du',      name: 'Double Unders',        category: 'Gimnásticos', equipment: 'Cuerda',  unit: 'reps' },
  { id: 'su',      name: 'Single Unders',        category: 'Gimnásticos', equipment: 'Cuerda',  unit: 'reps' },
  { id: 'situp',   name: 'Sit-up',               category: 'Gimnásticos', equipment: 'BW',      unit: 'reps' },
  { id: 'ghd',     name: 'GHD Sit-up',           category: 'Gimnásticos', equipment: 'GHD',     unit: 'reps' },
  { id: 'ghdext',  name: 'GHD Hip Extension',    category: 'Gimnásticos', equipment: 'GHD',     unit: 'reps' },
  { id: 'v-up',    name: 'V-Up',                 category: 'Gimnásticos', equipment: 'BW',      unit: 'reps' },
  { id: 'lsit',    name: 'L-Sit',                category: 'Gimnásticos', equipment: 'BW',      unit: 'seg' },
  { id: 'hollow',  name: 'Hollow Hold',          category: 'Gimnásticos', equipment: 'BW',      unit: 'seg' },
  { id: 'arch',    name: 'Arch Hold',            category: 'Gimnásticos', equipment: 'BW',      unit: 'seg' },

  // ─── CARDIO / MÁQUINAS ──────────────────────────────────────
  { id: 'row',    name: 'Remo',          category: 'Cardio', equipment: 'Remo',         unit: 'cals' },
  { id: 'rowm',   name: 'Remo (metros)', category: 'Cardio', equipment: 'Remo',         unit: 'metros' },
  { id: 'ski',    name: 'Ski Erg',       category: 'Cardio', equipment: 'Ski Erg',      unit: 'cals' },
  { id: 'bike',   name: 'Assault Bike', category: 'Cardio', equipment: 'Assault Bike', unit: 'cals' },
  { id: 'ecbike', name: 'Echo Bike',    category: 'Cardio', equipment: 'Echo Bike',    unit: 'cals' },
  { id: 'run',    name: 'Running',      category: 'Cardio', equipment: 'BW',           unit: 'metros' },
  { id: 'sprint', name: 'Sprint',       category: 'Cardio', equipment: 'BW',           unit: 'metros' },
  { id: 'swim',   name: 'Natación',     category: 'Cardio', equipment: 'BW',           unit: 'metros' },
];

export const CATEGORIES = ['Todos', 'Halterofilia', 'Powerlifting', 'Fuerza', 'Gimnásticos', 'Cardio'];

export const CATEGORY_COLORS = {
  Halterofilia: '#e63946',
  Powerlifting: '#9b5de5',
  Fuerza:       '#4895ef',
  Gimnásticos:  '#52b788',
  Cardio:       '#f4a261',
  Todos:        '#888899',
};
